server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.66:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

mybatis:
  tpyeAliasesPackage: com.springboot.pojo
